---
# set app specific ufw rules 
- name: Allow all access to tcp port 22
  community.general.ufw:
    rule: allow
    port: '22'
    proto: tcp

- name: Allow gluster private access to tcp port 24007
  community.general.ufw:
    rule: allow
    port: '24007'
    proto: tcp
    from_ip: "{{ item.instance.ip_priv1 }}"
  loop: "{{ gluster_data.server }}"

- name: Allow client private access to tcp port 24007
  community.general.ufw:
    rule: allow
    port: '24007'
    proto: tcp
    from_ip: "{{ item.instance.ip_pub1 }}"
  loop: "{{ gluster_data.client }}"
  when: client_ips is defined

- name: Allow gluster private access to tcp port 54207
  community.general.ufw:
    rule: allow
    port: '54207'
    proto: tcp
    from_ip: "{{ item.instance.ip_priv1 }}"
  loop: "{{ gluster_data.server }}"

- name: Allow client private access to tcp port 54207
  community.general.ufw:
    rule: allow
    port: '54207'
    proto: tcp
    from_ip: "{{ item.instance.ip_pub1 }}"
  loop: "{{ gluster_data.client }}"
  when: client_ips is defined


# async to avoid connection disruption
- name: Enable ufw
  community.general.ufw:
    state: enabled
  async: 60
  poll: 0