---
# roles/gluster/handlers

- name: restart glusterd
  systemd:
    name: glusterd
    state: restarted

- name: start gluster volume
  gluster.gluster.gluster_volume:
    state: started
    name: data-volume